version: '3.7'

services:
  oncallbuddyfinder:
    # this is used for delve forks
    security_opt:
      - seccomp:unconfined
    image: webofmars/oncall-buddy-finder:dev-rc
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
      #- "40000:40000"
    volumes:
      - ../secrets/oncall-budy-finder-fea585821673.json:/etc/oncall-buddy-finder/client_secret.json
      - ../secrets/config-docker.json:/etc/oncall-buddy-finder/config-docker.json
      #- /tmp/oncall-buddy-finder:/var/run/oncall-buddy-finder
    #entrypoint: ['/usr/local/bin/dlv', '--listen=:40000', '--headless=true', '--api-version=2', 'exec', '/usr/local/bin/oncall-buddy-finder']