version: '3'

services:

  oncallbuddyfinder:
    image: webofmars/oncall-buddy-finder:develop
    stdin_open: true
    tty: true
    volumes:
      - ../secrets/client_secret.json:/etc/oncall-buddy-finder/client_secret.json
      - ../secrets/config-docker.json:/etc/oncall-buddy-finder/config-docker.json
      - /tmp/oncall-buddy-finder:/var/run/oncall-buddy-finder
    #entrypoint: ash -c "while true; do echo '.'; sleep 2; done"
